seed: 2023
max_epochs: 100
gradient_clip_val: 0.5
accumulate_grad_batches: 2
batch_frequency: 100

logger:
  target: vidgen.utils.callbacks.VideoInterpolationLogger
  params:
    batch_frequency: 500
    downsample_factor: 0.5

model:
  target: vidgen.model.VideoModel
  params:
    lr: 0.0003
    use_vgg_loss: false
    cde_function:
      target: vidgen.modules.cde.ct_upsampler.ContinuousTimeUNet
      params:
        integration_method: euler
        step_size: 0.5
        rtol: 0.001
        atol: 0.001
        function:
          target: vidgen.modules.cde.ct_upsampler.CDEFunction
          params:
            in_channels: 4
            base_channels: 128
            channel_mults:
            - 1
            - 2
            - 4
        in_channels: 3
        latent_channels: 4
        base_channels: 128
        channel_mults:
        - 2
        - 4
        - 4

data:
  target: vidgen.data.multi.CollectiveDataloader
  params:
    dataloader_params:
      x4:
        num_workers: 8
        batch_size: 3
        shuffle: true
      vimeo:
        num_workers: 8
        batch_size: 3
        shuffle: true
      vimeo_septuplet:
        num_workers: 8
        batch_size: 3
        shuffle: true
      # vimeo_septuplet:
      #   num_workers: 8
      #   batch_size: 3
      #   shuffle: true
    datasets:
      # x4:
      #   path: dataset/X4K1000FPS
      #   num_frames: 9
      vimeo_septuplet:
        path: dataset/vimeo_septuplet
        septuplet: true
      vimeo:
        path: dataset/vimeo_triplet
