# General settings
seed: 2023

# Training settings
max_epochs: 10
gradient_clip_val: 0.5
accumulate_grad_batches: 1

# Saving intervals
batch_frequency: 100000000000 
log_batch_frequency: 10000000000

# Video saving downsample
downsample_factor: 0.5

model:
  target: vidgen.debug.DebugModel

data:
  target: vidgen.data.CollectiveDataloader
  params:
    num_workers: 8
    batch_size: 10
    shuffle: True
    datasets:
      kinetics:
        path: "dataset/UCF101/UCF-101"
        annotation_path: "dataset/UCF101/ucfTrainTestlist"
        metadata: "dataset/UCF101/UCF-101-metadata.pkl"
        num_frames: 10
        skip_frames: 4
